//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javabytes_prototype.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class javabytesDBEntities : DbContext
    {
        public javabytesDBEntities()
            : base("name=javabytesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_Line_Item> Order_Line_Item { get; set; }
        public virtual DbSet<Order_Line_Item_Product_Option_Link> Order_Line_Item_Product_Option_Link { get; set; }
        public virtual DbSet<Order_Status> Order_Status { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Option> Product_Option { get; set; }
        public virtual DbSet<Product_Option_Link> Product_Option_Link { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
