//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javabytes_prototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Line_Item = new HashSet<Order_Line_Item>();
        }
    
        public int order_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> delivery_collection { get; set; }
        public string delivery_location { get; set; }
        public Nullable<int> order_status_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> vendor_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Line_Item> Order_Line_Item { get; set; }
        public virtual Order_Status Order_Status { get; set; }
        public virtual User User { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
