//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javabytes_prototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Option_Link
    {
        public int product_option_link_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> product_option_id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product_Option Product_Option { get; set; }
    }
}
