//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javabytes_prototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Line_Item = new HashSet<Order_Line_Item>();
            this.Product_Option_Link = new HashSet<Product_Option_Link>();
        }
    
        public int product_id { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<int> vendor_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Line_Item> Order_Line_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Option_Link> Product_Option_Link { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
